### PR TITLE
Expression builder

### PR DESCRIPTION
**Pull request by mgaonach**
New version on the expression builder, allowing to view, copy, delete, edit and create expressions using drag&drop and/or text.

### CODE REVIEW

**Comment by mgaonach** [comment]
If you don't see any bug or problem, I think it's ready for merge.

**Comment by bowring** [comment]
also ...
we need to add brackets in a way similar to parentheses, so user can create in d-n-d:
5 + ["Expo"][0] . (we can do it in text edit already)

**Comment by bowring** [comment]
note that 5 + ["Expo"][0] is the same as 5 + ["Expo"]

**Comment by bowring** [comment]
also ...
when editing custom expression, if I copy exp, then clear exp, paste exp is empty?

**Comment by mgaonach** [comment]
I think the note tooltip could go in an other branch (we could also do a similar tooltip showing function arguments and outputs on hover - like netbeans does when hovering a function with ctrl pressed)

**Comment by bowring** [comment]
Great work

**Pull request merged**
