### PR TITLE
Expression Documents

### PR DESCRIPTION
**Pull request by ryanbarrett1515**
just created this so you can track progress and such

### CODE REVIEW

**Comment by bowring** [comment]
@ryanbarrett1515 - I updated this branch with master.

**Comment by bowring** [comment]
@ryanbarrett1515 - try the following as the html and image are in the same folder!  Also, use a checker such as netbeans on the the html - take a look at best practices and also consider xhtml and css3.

``` html
<img src="Hf1sabserr.jpeg"/>
```

**Comment by ryanbarrett1515** [comment]
careful when running the expression publisher main - it may take a minute: it will create about 8 megabytes of png images generated by the mathml, latex conversions of the expressions; and create a 72 kb html file after deserializing the squid project. It creates an html file with ALL of the expressions in that squid project

**Comment by bowring** [comment]
Making good progress!

**Comment by bowring** [comment]
I shared a solution on Overleaf:
https://www.overleaf.com/7245446721chvtcmmyrvnk

also see: 148 here: https://tex.stackexchange.com/questions/3782/how-can-i-split-an-equation-over-two-or-more-lines

happy problem solving !

**Comment by ryanbarrett1515** [comment]
The problem is that the latex to image converter doesn't recognize statements such as \usepackage{breqn}. So to make it span multiple lines I would have to use hard breaks only and hard breaks don't give proper alignment. I think the best option is to just make the pdf wider since that doesn't seem to be making the pdf file sizes any larger for whatever reason (I don't know the internal implementation of pdfs) and a lot of the equations are oversized anyways.

**Comment by ryanbarrett1515** [comment]
There would still be a risk of runoff even with the equations spanning multiple lines

**Comment by bowring** [comment]
making progress ...  good work

**Comment by bowring** [comment]
@ryanbarrett1515 -

Looking great!  Let's do the following:

1) concentrate on producing single reports by placing the "Show PDF Report" button next to "Show in Browser" button.
2) disable the html version at least for now
3) add .png files to .gitignore
4) the new button will create and open the pdf (use BrowserControl.showURI method of Squid).  Note - this method needs to be updated to handle the Linux issue #198 - do as separate pull request.
5) the pdf is missing a check in the checkboxes
6) add a footer that names the project, task, date, etc.
7) output the pdf as [expressionName].pdf into a new folder that you will create in the folder structure for Squid3_Reports:
     PROJECT-blah
          TASK-blah
               REPORTS-per-Squid2
               REPORTS-Expressions               << new folder

See you Wed.

**Comment by bowring** [comment]
@ryanbarrett1515 - in the latest master you will see a new button at the top right of expression manager for "Show Dependency Graphs".  When you are ready adapt this button to be "Show Expression Details" and add the dependency graphs to your layout.

**Comment by bowring** [comment]
Please clean up after my mistake on fixing merge conflict - in ExpressionBuilder, run fix imports!

Also, not sure what progress has been made - I don't see the dependency trees in test.html for example. Also there is a transformer exception appearing.  

What is the plan from here?

**Comment by ryanbarrett1515** [comment]
I changed the pathing and added an init xsltml method for functionality in the actual app - the main method in expression publisher won't work right now (I can fix that if you want so we can keep using it for easier testing). The show html button next to show in browser in the expression builder works. Here's a screenshot I just took after using that button:
Screenshot (27)

**Comment by bowring** [comment]
OK, but I am still getting this "Transformer Error" inside the html because of this:
ERROR:  'Could not compile stylesheet'
/Development/Squid/squidApp/XSLTML/mmltex.xsl (No such file or directory)
FATAL ERROR:  '/Development/Squid/squidApp/XSLTML/mmltex.xsl (No such file or directory)'

**Comment by ryanbarrett1515** [comment]
When you run squid is this not printed out to the terminal?
XSLTML File added: cmarkup.xsl
XSLTML File added: entities.xsl
XSLTML File added: glayout.xsl
XSLTML File added: mmltex.xsl
XSLTML File added: scripts.xsl
XSLTML File added: tables.xsl
XSLTML File added: tokens.xsl

I'm doing the same thing for the XSLTML files as we're doing for the schemas

No need to worry about the png files at all anymore - I'm now using base64 encoding to put the image content directly in the html files (this also will make it so that the image path isn't messed up when people save the html files in different directories, move them around, etc).

**Comment by bowring** [comment]
still getting -
ERROR:  'Could not compile stylesheet'
/Development/Squid/squidApp/XSLTML/mmltex.xsl (No such file or directory)

suggest your clear out your files and see why these are not getting written

**Comment by bowring** [comment]
look at line 57 of .gitignore !

**Comment by ryanbarrett1515** [comment]
listOfXSLTMLFiles.txt was ignored! it should definitely work now; i'm handling it exactly like our schemas just forgot to add that file to the .gitignore

**Comment by bowring** [comment]
that's better!

please revisit https://docs.google.com/drawings/d/1FHPaweZ4MP2P_Qipuck24_SR7HcjdQKeEX-nm8_JfhY/edit

and let's improve the look and feel of the output ... note you use the word target twice!  check the specs above

**Comment by bowring** [comment]
It is getting there.  

1) The ref mat checkbox does not show checked in html.
2) I would like to see the look and feel improved - the line showing the switches is crowded
3) There should be a slight indentation for the contents of each section
4) these should be a header  something like "Squid3 Expression Details Report" etc
5) there should be a footer with the date and the squid project file name, etc.

**Pull request merged**
