### PR TITLE
Issue403

### PR DESCRIPTION
**Pull request by ryanbarrett1515**

### CODE REVIEW

**Comment by bowring** [comment]
two problems:

1) disable "rename" on multiple choices - really just need delete

2) see logic for special case of first 4 categories in Weighted Mean Plot and Sort report (new name) - deletion should not be allowed for these 4.

**Comment by bowring** [comment]
@ryanbarrett1515 - so far so good!  need to prevent drag-n-drop into fixed category columns

**Comment by bowring** [comment]
first click of Wm Plot and Sort report throws a null pointer exception

**Comment by ryanbarrett1515** [comment]
I'm not getting any exceptions

**Comment by bowring** [comment]
nice ... I am merging;

**Pull request merged**
