### PR TITLE
My second branch 

### PR DESCRIPTION
**Pull request by NicoleRayner**
AgePb76 definition edit and .gitignore

### CODE REVIEW

**Comment by bowring** [comment]
@NicoleRayner -  Not sure why you are removing reference to uncertainty in the definition as it is in the output array of this function?

**Comment by bowring** [comment]
I see on a more close comparison with AgePb76WithErr that AgePb76 does the same calculation with a zero uncertainty - good catch!  We need to edit the labelsForInputValues and  labelsForOutputValues as well to match argument count = 1.

**Comment by NicoleRayner** [comment]
I noticed only one input argument, but not the output values.  I can tweak those as I see them.

**Comment by bowring** [comment]
should i wait for update to this pull request?

**Comment by bowring** [comment]
I decided to put a more detailed explanation of the definition for clarity and documentation.

**Pull request merged**
