### PR TITLE
additional expression xml functionality - custom expressions imp/exp in groups

### PR DESCRIPTION
**Pull request by ryanbarrett1515**
expression menu items added, both are functional; exporting custom expressions will almost always cause filenotfoundexceptions to be thrown, this is caused by incorrect file names, i'm going to wait for my feature2 pull request to be brought over so i can use the filename fixer i created on that branch to fix this

### CODE REVIEW

**Comment by bowring** [comment]
Good start, but needs work.  Fails because the logic here is flawed in the second line:
``` java
public void exportCustomExpressions(File folder) {
        if(folder != null && folder.mkdirs()) {
```
Note that mkDirs() returns false if folder exists !
Also, any call to mkDirs() should be by itself so you can handle the outcome robustly.
Also, use the debugger to see what 
``` java
System.getProperty("user.home")
```
returns - it may already have delimiter at the front

Tutorial: https://o7planning.org/en/11129/javafx-filechooser-and-directorychooser-tutorial

**Comment by bowring** [comment]
Nothing gets exported.

**Comment by bowring** [comment]
Good start, needs some improvements

1) the user needs the option to confirm or deny import of each expression which already exists (you can see how this is done on the single load expression from xml menu item) AND be able to click a checkbox that says "do this for all" where "this" is overwrite or don't overwrite.

2) each expression 'exp' that is imported needs to have these task methods called, depending on the circumstance (if new, don't need to remove):

```java
        removeExpression(exp);

        taskExpressionsOrdered.add(exp);
        updateAffectedExpressions(exp);
        updateAllExpressions();

// then, after all exp are processed
        setChanged(true);
        setupSquidSessionSpecsAndReduceAndReport();

// instead of just 
         taskexpressionOrdered.add(exp)

```

3) after adding all the expressions per above , these calls need to be made inside squiUIController:
```java
        buildExpressionMenuMRU();
        launchExpressionBuilder();
        showUI(expressionBuilderUI);
```
4) the interaction with the folder chooser is clunky - when I go to import from folder, the file chooser opens the folder containing the files instead of its parent; the same thing happens when I try to export a second time - you need to store the MRU = parent of folder

5) you can test all this by using the context menu to remove a few of the custom expressions and then try your importer.

6) consider for a next project (not this iteration) to improve this interaction by showing a form with all the custom expressions listed by name each with a checkbox to allow the user to select which of the expressions gets exported from the folder;  we could then do the same for importing and include the overwrite option there as well.

**Comment by ryanbarrett1515** [comment]
I made all those changes except instead of a checkbox i had 2 buttons for replace all or replace none since I also added a button for renaming

**Comment by bowring** [comment]
Looks great!  Good work.

Now, take a look at this logic and its simplification below:
```java
            File[] files = folder.listFiles(f -> {
                boolean retVal;
                if (f.getName().toLowerCase().endsWith(".xml")) {
                    retVal = true;
                } else {
                    retVal = false;
                }
                return retVal;
```

should be:
```java
            File[] files = folder.listFiles(f -> {
                return f.getName().toLowerCase().endsWith(".xml");
```

Then we need a more extensive test in this filter - as a static method in a new class in core / utilities / fileutilities (say class FileValidator) : 
method = public static boolean validateFileIsXMLSerializedEntity(File serializedFile, Class entityClass)

In this method confirm that the file is of the correct type, i.e. an expression.
We will be able to use this test on other serialized objects as well.

This will prevent the accidental processing of other xml files.  We also need to catch the exception that might happen if the xml file does not deserialize correctly.

Keep up the good work.

**Comment by ryanbarrett1515** [comment]
While the filter may not keep out non Expression xml files, this issue is handled further down: 
Non expression xml files won't be (fully) parsed, of course won't be  added, and "<filename> custom expression not added" will be printed to the terminal.

Do you have any tips for how to create this general purpose validateFileIsXMLSerializedEntity method? I am not sure it is entirely possible; elements can have various names and fields could be omitted. JDOM and XStream don't seem to have any way to tell the class or type of elements (root or otherwise).

**Comment by bowring** [comment]
validate the expression xml file against the schema as per PrawnFileHandler.java line 126

**Comment by bowring** [comment]
also, you are introducing conflicts - make sure you are up to date

**Comment by bowring** [comment]
I used our perm1 example and exported 26 expressions;  on filtering only 16 passed muster;  it appears we need to add the enumerated type "value" to the list of operations in the schema.  When I do that, 25 of 26 pass the filter.  You need to discover what is the missing file that does not pass and why.  Also, given this issue, we should have a test written for the export/import of expressions to make sure all that are written out can be read back in.
```xml
<xs:enumeration value="value" />
```

**Comment by ryanbarrett1515** [comment]
The 1 other expression that isn't passing seems to not be passing simply because the value is AgePb76 not agePb76 - simple case issue. What do you want me to do about this? Should the A be a capital in the schema?

**Comment by bowring** [comment]
dang ... we need to support case-insensitivity (which we do in the java code and grammar see the file ExpressionsForSquid2.g4 lines 80 - 141).  However, it does not seem that XML schema support this.  the solution for now is to abandon using the operationType (leave in schema) and change the type of Operation to String.  We really only need this schema as a filter, as Squid does a full parse and grammar check and will catch any errors introduced.

**Comment by bowring** [comment]
See my note above - leave the enumeration in the schema (with a comment to this effect) , just not used.  Later we will solve this problem with notion that Squid drives the serialization, so Squid can control the case of the operations written in the XML documents.  In the short-term however, we will bypass this refinement.  Also,  travis is failing the build on the new test.

**Comment by ryanbarrett1515** [comment]
I believe I have addressed everything now

**Comment by bowring** [comment]
Great work.

**Pull request merged**
