### PR TITLE
Squid Parameters Manager

### PR DESCRIPTION
**Pull request by ryanbarrett1515**

### CODE REVIEW

**Comment by bowring** [comment]
the test writesReportsFromPrawnFile fails because of a call to new Task()... not sure yet what the issue is

1) do make sure to change the left side of your model declarations to "ParametersModel":
public void setReferenceMaterial(ParametersModel refMat);
    public ParametersModel getReferenceMaterial();
    public void setPhysicalConstantsModel(ParametersModel physConst);
    public ParametersModel getPhysicalConstantsModel();
    public void setCommonPbModel(ParametersModel model);
    public ParametersModel getCommonPbModel();

2) be sure to rename PbBlankICModel to be commonPb

3) the problem is when you use public static PhysicalConstantsModel defaultPhysicalConstantsModel = getDefaultModel("EARTHTIME Physical Constants Model", "1.1");
 
make this call as part of the task constructor instead ... then you can test if it excepts or not

4) also I am getting many exceptions from XStream - I deleted my lab data and started the app and 
the build fails

**Comment by bowring** [comment]
caveat to that last comment - it works when I restore your code ... the problem is with the design not supporting the test mode as discussed.

**Comment by bowring** [comment]
suggestion -  make "sigfigs" a spinner from 1 to 12; as it is you can enter negative numbers; a spinner is more elegant . (see task manager for example - use integer instead of double tho)

**Comment by bowring** [comment]
looking good overall

**Comment by bowring** [comment]
Common Pb needs additional ratios:
207Pb/206Pb
208Pb/206Pb

**Comment by bowring** [comment]
It would help readability if a light grid appeared in the tables

**Comment by bowring** [comment]
Great work!

1) if you open common lead first, the menu items under edit are not properly initialized relative to enable
2) let's make physical constants the third flavor in menus and tabs
3) change all left-side references to the class ParametersModel and then
add another attribute for Task:
    protected ParametersModel concentrationReferenceMaterial;
    this is not a new model type, rather the task will have two referenceModels
4) make class ParameterModels abstract
5) in ParameterModels, chain the constructors so you do not repeat assignments - see Task constructors for example)
6) the location calculations for the labdata window do not change when the window moves; also, if I have it open and then click on a menu item, it jumps to a new location
7) add a space between Squid and LabData in the menu

that's it for now...

**Comment by ryanbarrett1515** [comment]
When you "save and register" a current edit, it will be saved in the .ser file in squid3 user data. You can export as xml through the file menu... I can change how that works if you want.

**Comment by bowring** [comment]
Looking great!

A couple tweaks:
1) detect if the four models are null in a task (i.e. any existing task from before this lab data) and set them to the defaults.

2) The drop downs for Ref Mat (and probably the others) are not showing names in correct order.

3) I chose a model for each and saved the project and exited Squid.  When I re-opened, the drop down boxes did not display my choices until I clicked on them.  I realize we are going to have to add small labels to the left of each (Ref Mat, Conc Ref Mat, Phys Const, Common Pb) also.

Almost there!

**Comment by bowring** [comment]
Great work by @ryanbarrett1515 !

**Pull request merged**
