### PR TITLE
Parameters Models Testing

### PR DESCRIPTION
**Pull request by ryanbarrett1515**

### CODE REVIEW

**Comment by ryanbarrett1515** [comment]
I've no idea why the tests aren't passing on travis ci. They're passing on my computer and don't use any file operations.

**Comment by bowring** [comment]
do you need me to review?

**Comment by ryanbarrett1515** [comment]
yeah, thanks

**Comment by bowring** [comment]
Run debug test mode and step through your ParametersManagerTests and you will see the issues;

Also, the tests should simply load the model, build an expression for a parameter and test if the expression has the correct model value instead of changing a value

see BuiltInExpressionsFactory, lines 387 - 401 for example of how to build expression from model

**Pull request merged**
