### PR TITLE
WM SVG generator

### PR DESCRIPTION
**Pull request by drakene**
Should be good to go... no issues that I see on my end.

### CODE REVIEW

**Comment by bowring** [comment]
You need to delete the .svg files from your repo so they disappear from the pull request

**Comment by drakene** [comment]
Ah yes, I forgot about that. It should be good now! Sent from Mail for Windows 10 From: Jim BowringSent: Tuesday, January 19, 2021 4:01 PMTo: CIRDLES/SquidCc: Noah Drake; AuthorSubject: Re: [CIRDLES/Squid] WM SVG generator (#545) You need to delete the .svg files from your repo so they disappear from the pull request—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bowring** [comment]
@drakene - still need to remove mouse menu ;-) Great job!

**Comment by drakene** [comment]
Of course I forgot! It's gone now... should be all good now.

**Pull request merged**
