### PR TITLE
Squid lab data

### PR DESCRIPTION
**Pull request by ryanbarrett1515**

### CODE REVIEW

**Comment by bowring** [comment]
@ryanbarrett1515 - you need to replace your version of squidCore/src/main/resources/org/cirdles/squid/projects/Z626611PKPERM1.squid with the one from master branch.  Somehow you got a polluted version, which is leading to failed tests.

**Comment by bowring** [comment]
Looks good: make sure that as a result of check / uncheck for Reference Dates that the correct tab then gets the focus.

**Comment by ryanbarrett1515** [comment]
we need to be careful with calling calculateApparentDates as doing so will overwrite any user created reference dates

**Comment by bowring** [comment]
The solution is to introduce a boolean  that captures whether or not the model is "Reference" or not i.e., test for the state of the model based on the checkbox choice.  Then, apparent date method can check that boolean.  Also, can you take care of replacing the bad squid file in resources in your branch?

**Comment by bowring** [comment]
Also, for Reference Material concentrations, we need to alert the user that units = 'ppm' (parts per million) - possibly as simply as 'conU ppm'

**Pull request merged**
