### PR TITLE
Report table schema

### PR DESCRIPTION
**Pull request by drakene**
Validation for report tables, as well as an added attribute for SquidReportTable objects which keeps track of the table's targeted spots (unknowns or reference materials). Also, I add a feature which automatically makes the ReportSettingsController display the expressions of the targeted spots of an imported table.

### CODE REVIEW

**Comment by bowring** [comment]
@drakene - good work; almost there, but we need to handle nested columns for uncertainty:
1) in SquidReportColumnXMLConverter, 
line 26 s.b. 
```java
writer.setValue(""); 
```
and line 62 s.b. 
```java
if (reader.getValue().length() > 0) {
```

2. the schema needs to be modified to introduce a new type for SquidReportColumn, so the body of the xsd will contain:
```xml
    <xs:element name="SquidReportTable">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reportTableName" type="xs:string" />
                <xs:element name="reportCategories">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="reportCategory">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="displayName" type="xs:string" />
                                        <xs:element name="categoryColumns">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">                                                  
                                                    <xs:element name="SquidReportColumn" type="SquidReportColumn" minOccurs="0"/>                                                                                                      
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="visible" type="xs:boolean" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="reportSpotTarget" type="spotTypes" />
                <xs:element name="isDefault" type="xs:boolean" />
                <xs:element name="version" type="xs:int" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
  
    <xs:complexType name="SquidReportColumn">
        <xs:sequence minOccurs="0">
            <xs:element name="expressionName" type="xs:string" />
            <xs:element name="units" type="xs:string" />
            <xs:element name="uncertaintyColumn" type="SquidReportColumn" />
            <xs:element name="amUncertaintyColumn" type="xs:boolean" />
            <xs:element name="uncertaintyDirective" type="xs:string" />
            <xs:element name="countOfSignificantDigits" type="xs:int" />
            <xs:element name="visible" type="xs:boolean" minOccurs="0" />
            <xs:element name="footnoteSpec"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="spotTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REFERENCE_MATERIAL" />
            <xs:enumeration value="UNKNOWN" />
            <xs:enumeration value="NONE" />
        </xs:restriction>
    </xs:simpleType>
```

**Comment by bowring** [comment]
@drakene - you mentioned you had an update to push?

**Comment by drakene** [comment]
I just double checked and it looks like I made the changes I needed. I should be good here as well.

**Comment by bowring** [comment]
Two more things:
1) in SquidReportTableXMLConverter.java, line 68, missing a 
```java 
reader.moveDown();
```

2) write a test or two to make sure this all works

**Comment by drakene** [comment]
Before I resolve the merge conflict, would you like me to use the JAXB validation for report tables and tasks? I can't remember if you said it was ok for me to use the old method, [validateFileIsSerializedXMLEntity](https://github.com/CIRDLES/Squid/blob/master/squidCore/src/main/java/org/cirdles/squid/utilities/fileUtilities/FileValidator.java) and sadly it appears I neglected write anything down regarding this issue during our meeting.

**Pull request closed without merging**
